//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace server.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("server.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMM|RED|0|0
        ///COMM|RED|1|1
        ///COMM|RED|2|2
        ///COMM|RED|3|3
        ///COMM|RED|4|4
        ///COMM|RED|5|5
        ///COMM|RED|6|6
        ///COMM|RED|7|7
        ///COMM|RED|8|8
        ///COMM|RED|9|9
        ///COMM|RED|1|1
        ///COMM|RED|2|2
        ///COMM|RED|3|3
        ///COMM|RED|4|4
        ///COMM|RED|5|5
        ///COMM|RED|6|6
        ///COMM|RED|7|7
        ///COMM|RED|8|8
        ///COMM|RED|9|9
        ///COMM|BLUE|0|0
        ///COMM|BLUE|1|1
        ///COMM|BLUE|2|2
        ///COMM|BLUE|3|3
        ///COMM|BLUE|4|4
        ///COMM|BLUE|5|5
        ///COMM|BLUE|6|6
        ///COMM|BLUE|7|7
        ///COMM|BLUE|8|8
        ///COMM|BLUE|9|9
        ///COMM|BLUE|1|1
        ///COMM|BLUE|2|2
        ///COMM|BLUE|3|3
        ///COMM|BLUE|4|4
        ///COMM|BLUE|5|5
        ///COMM|BLUE|6|6
        ///COMM|B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Deck {
            get {
                return ResourceManager.GetString("Deck", resourceCulture);
            }
        }
    }
}
